version: 2

jobs:

  build:
    docker:
      - image: python:3.6.0
    steps:
      - checkout
      - run: pip install git+https://github.com/OCR-D/core
      - run: make validate

workflows:
  version: 2
  build:
    jobs:
      - build
