version: 2

jobs:

  build:
    docker:
      - image: python:3.8.0
    steps:
      - checkout
      - run: git clone --depth 1 https://github.com/OCR-D/core; cd core; make install;cd ..;rm -rf core
      - run: make validate

workflows:
  version: 2
  build:
    jobs:
      - build
