rebuild:
	cd data ; \
	ocrd-olena-binarize -l DEBUG --overwrite -P impl kim              -I OCR-D-IMG -O OCR-D-PRE-BIN-KIM ;\
	ocrd-olena-binarize -l DEBUG --overwrite -P impl niblack          -I OCR-D-IMG -O OCR-D-PRE-BIN-NIBLACK ;\
	ocrd-olena-binarize -l DEBUG --overwrite -P impl otsu             -I OCR-D-IMG -O OCR-D-PRE-BIN-OTSU ;\
	ocrd-olena-binarize -l DEBUG --overwrite -P impl sauvola          -I OCR-D-IMG -O OCR-D-PRE-BIN-SAUVOLA ;\
	ocrd-olena-binarize -l DEBUG --overwrite -P impl sauvola-ms       -I OCR-D-IMG -O OCR-D-PRE-BIN-SAUVOLA-MS ;\
	ocrd-olena-binarize -l DEBUG --overwrite -P impl sauvola-ms-fg    -I OCR-D-IMG -O OCR-D-PRE-BIN-SAUVOLA-MS-FG ;\
	ocrd-olena-binarize -l DEBUG --overwrite -P impl sauvola-ms-split -I OCR-D-IMG -O OCR-D-PRE-BIN-SAUVOLA-MS-SPLIT ;\
	ocrd-olena-binarize -l DEBUG --overwrite -P impl singh            -I OCR-D-IMG -O OCR-D-PRE-BIN-SINGH ;\
	ocrd-olena-binarize -l DEBUG --overwrite -P impl wolf             -I OCR-D-IMG -O OCR-D-PRE-BIN-WOLF
